language: node_js
node_js:
- '0.12'
sudo: false
cache:
  directories:
  - node_modules
before_install:
- export PATH=/usr/local/phantomjs-2.0.0/bin:$PATH
- npm config set spin false
- npm install -g npm@^2
install:
- npm install -g bower
- npm install
- bower install
script:
- bash ./deploy-to-ghpages.sh
env:
  global:
  - COMMIT_AUTHOR_EMAIL: mauro@sdf.org
  - GITHUB_USER: lvm
  - GITHUB_REPO: lvm/site-dataset-arte-electronico-argentino
  - secure: usRwfZ0epavYKGYqaoGOjEYMffmGmQhopdfZQcP31siJolX+Knibiq+PZhainEjsAW6Fy0cX6CXNgiI7yIFZsMKBhup7ZOtnIAIIdQbLRkIJzLV6QzxvOwLRtgPVfwqyKNU+F1C8O4jEfJYle7EqJCcS1keutnW/JIxFShRztRWc7+GI8WqP2ebZhQ/9e6oLzn+uyNs+crWvwrB1OssvmvE5PKdsM9J5A6fF0Vli0nMsrFSTWKRVwFmCFLMTtxETlaVXja5+i9bKRioiebtN7AjMvZPmS5nPAr6UyMCMQgZECIqdmi0/a6RTjdIuFL85cdr0cWFDuy25JKd/3s4QL0ifKDRUQTSl52q19SObGyxDTX7cOYVQ1/qZ/21WrjtWzQf0HqyHH3hnEt3qrJY2eEbbPjLEJKKjJW8If+n5bB4X1/r3sgtjoQLmJ2CQFMotQSnSf+MizLNOGDndCeava0lSbpJim0yhQSwODuCtk7+7crXRkcb5KPKrsWyob3fy1dDLmkDfiTXHNYAnpTKLDwm1QA2f6R+s33vlni50rFjf5/MPCwd1nXFjRSHiyAJvaPUVMl/so7bJ0uagrPB4XiFyIpD0LgFCaUtFwolpRnmUNPhnbLGJUaHvlz2psgCYI2q0rJW4xtRM18LFEWTUquQ1A6EK+hdfc3AJ+rIRXdw=
